Repository smileidentity/ios, pull requests merged in 2024-12, with the labels that each got.

#262 Fix UserID Refresh for New Jobs
  Example/SmileID.xcodeproj/project.pbxproj
  Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreen.swift
  Example/SmileID/EnhancedKYC/EnhancedKycWithIdInputScreen.swift
  Example/SmileID/Home/HomeView.swift
  Example/SmileID/Home/HomeViewModel.swift
  Example/SmileID/Info.plist
  Sources/SmileID/Classes/Consent/OrchestratedConsentScreen.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieSubmissionManager.swift
  Sources/SmileID/Classes/SelfieCapture/View/OrchestratedSelfieCaptureScreen.swift
  Sources/SmileID/Classes/SelfieCapture/View/SelfieCaptureScreen.swift
  Sources/SmileID/Classes/SmileID.swift
  Sources/SmileID/Classes/Views/SearchableDropdownSelector.swift
Labels: Review effort [1-5]: 3

#263 Device Motion Orientation
  Example/SmileID.xcodeproj/project.pbxproj
  Sources/SmileID/Classes/FaceDetector/LivenessCheckManager.swift
  Sources/SmileID/Classes/Networking/Models/v2/Metadata.swift
  Sources/SmileID/Classes/SelfieCapture/CaptureGuideAnimation.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SmileID.swift
  Sources/SmileID/Resources/Localization/en.lproj/Localizable.strings
  Sources/SmileID/Resources/LottieFiles/headdirection_with_bg.lottie
  Sources/SmileID/Resources/LottieFiles/light_animation.lottie
  Sources/SmileID/Resources/LottieFiles/liveness_guides.lottie
  Sources/SmileID/Resources/LottieFiles/positioning.lottie
  Sources/SmileID/Resources/LottieFiles/positioning_with_bg.lottie
Labels: Review effort [1-5]: 3

#264 Fixed Missing Document Type
  CHANGELOG.md
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
Labels: Review effort [1-5]: 1

#266 Fix Selfie and Liveness Image Sizes, Fix Layout for Small Screen Devices
  CHANGELOG.md
  Example/SmileID/Home/ProductCell.swift
  Sources/SmileID/Classes/Camera/CameraManager.swift
  Sources/SmileID/Classes/DocumentVerification/Model/DocumentCaptureViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
  Sources/SmileID/Classes/FaceDetector/EnhancedFaceDetector.swift
  Sources/SmileID/Classes/FaceDetector/FaceValidator.swift
  Sources/SmileID/Classes/Helpers/SmileIDResourcesHelper.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModelAction.swift
  Sources/SmileID/Classes/SelfieCapture/SmartSelfieResultDelegate.swift
  Sources/SmileID/Classes/SelfieCapture/View/EnhancedSelfieCaptureScreen.swift
  Sources/SmileID/Classes/SelfieCapture/View/FaceBoundingArea.swift
  Sources/SmileID/Classes/SelfieCapture/View/SelfieActionsView.swift
  Sources/SmileID/Classes/SelfieCapture/View/SelfiePreviewView.swift
  Sources/SmileID/Classes/SelfieCapture/View/SubmissionStatusView.swift
  Sources/SmileID/Classes/SelfieCapture/View/UserInstructionsView.swift
  Sources/SmileID/Resources/Localization/en.lproj/Localizable.strings
  Sources/SmileID/Resources/Media.xcassets/Checkmark.imageset/Checkmark.png
  Sources/SmileID/Resources/Media.xcassets/Checkmark.imageset/Checkmark@2x.png
  Sources/SmileID/Resources/Media.xcassets/Checkmark.imageset/Checkmark@3x.png
  Sources/SmileID/Resources/Media.xcassets/Checkmark.imageset/Contents.json
  Sources/SmileID/Resources/Media.xcassets/Xmark.imageset/Contents.json
  Sources/SmileID/Resources/Media.xcassets/Xmark.imageset/Xmark.png
  Sources/SmileID/Resources/Media.xcassets/Xmark.imageset/Xmark@2x.png
  Sources/SmileID/Resources/Media.xcassets/Xmark.imageset/Xmark@3x.png
Labels: Review effort [1-5]: 3

#265 Adding Active Liveness Metadata
  Sources/SmileID/Classes/Camera/CameraManager.swift
  Sources/SmileID/Classes/Networking/Models/v2/Metadata.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
Labels: Review effort [1-5]: 2

#268 SmileID Enhanced Views
  Example/SmileID/Home/HomeView.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieSubmissionManager.swift
  Sources/SmileID/Classes/SelfieCapture/View/OrchestratedEnhancedSelfieCaptureScreen.swift
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort [1-5]: 3

#270 Release 10.3.1
  Example/Podfile.lock
  SmileID.podspec
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort [1-5]: 1

#271 Fix Flutter Issues
  CHANGELOG.md
  Example/Podfile.lock
  Example/SmileID/Home/HomeViewModel.swift
  SmileID.podspec
  Sources/SmileID/Classes/Networking/APIError.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/View/EnhancedSelfieCaptureScreen.swift
  Sources/SmileID/Classes/SelfieCapture/View/SelfieCaptureScreen.swift
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort [1-5]: 1

#272 Fix Cancel Action on Error
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieSubmissionManager.swift
Labels: Review effort [1-5]: 2

#273 Feedback and SPM Fixes
  Example/Podfile.lock
  Example/SmileID.xcodeproj/project.pbxproj
  SmileID.podspec
  Sources/SmileID/Classes/FaceDetector/EnhancedFaceDetector.swift
  Sources/SmileID/Classes/FaceDetector/SelfieQualityDetector.swift
  Sources/SmileID/Classes/SelfieCapture/View/LivenessCaptureInstructionsView.swift
  Sources/SmileID/Resources/Localization/en.lproj/Localizable.strings
  Sources/SmileID/Resources/ML/SelfieQualityDetector.mlmodelc/analytics/coremldata.bin
  Sources/SmileID/Resources/ML/SelfieQualityDetector.mlmodelc/coremldata.bin
  Sources/SmileID/Resources/ML/SelfieQualityDetector.mlmodelc/metadata.json
  Sources/SmileID/Resources/ML/SelfieQualityDetector.mlmodelc/model.espresso.net
  Sources/SmileID/Resources/ML/SelfieQualityDetector.mlmodelc/model.espresso.shape
  Sources/SmileID/Resources/ML/SelfieQualityDetector.mlmodelc/model.espresso.weights
  Sources/SmileID/Resources/ML/SelfieQualityDetector.mlmodelc/model/coremldata.bin
  Sources/SmileID/Resources/ML/SelfieQualityDetector.mlmodelc/neural_network_optionals/coremldata.bin
Labels: Review effort [1-5]: 2

#274 chore: release v10.3.3
  CHANGELOG.md
  Example/Podfile.lock
  SmileID.podspec
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort [1-5]: 1
