Repository smileidentity/ios, pull requests merged in 2025-02, with the labels that each got.

#287 Fix UserID and JobID Not Refreshing
  Example/SmileID.xcodeproj/project.pbxproj
  Example/SmileID/Home/HomeView.swift
Labels: Review effort [1-5]: 1

#292 Add Consent Information to EnhancedDocV 📸
  CHANGELOG.md
  Example/SmileID/DocumentVerification/EnhancedDocumentVerificationWithSelector.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort [1-5]: 2, Possible security concern

#295 Use StateObject for SDK Views
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift
  Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift
Labels: Review effort [1-5]: 2

#294 Objective-C Sample Project
  Example-Objc/Example-Objc.xcodeproj/project.pbxproj
  Example-Objc/Example-Objc.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Example-Objc/Example-Objc/AppDelegate.h
  Example-Objc/Example-Objc/AppDelegate.m
  Example-Objc/Example-Objc/Assets.xcassets/AccentColor.colorset/Contents.json
  Example-Objc/Example-Objc/Assets.xcassets/AppIcon.appiconset/Contents.json
  Example-Objc/Example-Objc/Assets.xcassets/Contents.json
  Example-Objc/Example-Objc/Base.lproj/LaunchScreen.storyboard
  Example-Objc/Example-Objc/Base.lproj/Main.storyboard
  Example-Objc/Example-Objc/Info.plist
  Example-Objc/Example-Objc/SceneDelegate.h
  Example-Objc/Example-Objc/SceneDelegate.m
  Example-Objc/Example-Objc/SmileID/EnhancedSelfieCaptureViewController.swift
  Example-Objc/Example-Objc/SmileID/Example-Objc-Bridging-Header.h
  Example-Objc/Example-Objc/SmileID/SmartSelfieCaptureViewController.swift
  Example-Objc/Example-Objc/SmileID/SmileIDManager.h
  Example-Objc/Example-Objc/SmileID/SmileIDManager.m
  Example-Objc/Example-Objc/ViewController.h
  Example-Objc/Example-Objc/ViewController.m
  Example-Objc/Example-Objc/main.m
  Example-Objc/README.md
  Example/SmileID.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Review effort [1-5]: 2

#288 SDK Navigation Improvements for Selfie Capture Jobs
  Example/SmileID/Home/HomeView.swift
  Example/SmileID/Home/HomeViewController.swift
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift
  Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift
  Sources/SmileID/Classes/Helpers/BindingExtensions.swift
  Sources/SmileID/Classes/Helpers/NavigationHelper.swift
  Sources/SmileID/Classes/Networking/APIError.swift
  Sources/SmileID/Classes/SelfieCapture/OrchestratedSelfieCaptureConfig.swift
  Sources/SmileID/Classes/SelfieCapture/OrchestratedSelfieCaptureViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieCaptureConfig.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieCaptureResult.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SmartSelfieResultDelegate.swift
  Sources/SmileID/Classes/SelfieCapture/View/OrchestratedEnhancedSelfieCaptureScreen.swift
  Sources/SmileID/Classes/SelfieCapture/View/OrchestratedSelfieCaptureScreen.swift
  Sources/SmileID/Classes/SelfieCapture/View/SefieCaptureProcessingView.swift
  Sources/SmileID/Classes/SelfieCapture/View/SelfieCaptureScreen.swift
  Sources/SmileID/Classes/SelfieCapture/View/SmartSelfieInstructionsScreen.swift
  Sources/SmileID/Classes/SelfieCapture/ViewModel/SelfieCaptureResultStore.swift
  Sources/SmileID/Classes/SmileID.swift
  Sources/SmileID/Classes/Views/ImageCaptureConfirmationDialog.swift
  Sources/SmileID/Classes/Views/ProcessingScreen.swift
Labels: Review effort [1-5]: 4
