Repository smileidentity/ios, pull requests merged in 2025-04, with the labels that each got.

#311 Fix Error Callback
  CHANGELOG.md
  Example/Podfile
  Example/Podfile.lock
  Example/SmileID.xcodeproj/project.pbxproj
  SmileID.podspec
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort 2/5

#310 Metadata: Proxy and VPN Detection
  Example/Podfile
  Example/Podfile.lock
  Sources/SmileID/Classes/Helpers/NetworkMetadataProvider.swift
  Sources/SmileID/Classes/Metadata/IPAddressProvider.swift
  Sources/SmileID/Classes/Metadata/MetadataKey.swift
  Sources/SmileID/Classes/Metadata/MetadataManager.swift
  Sources/SmileID/Classes/Metadata/MetadataModels.swift
  Sources/SmileID/Classes/Metadata/Metadatum.swift
  Sources/SmileID/Classes/Metadata/NetworkMetadataProvider.swift
  Sources/SmileID/Classes/Metadata/UIDeviceExtension.swift
Labels: Review effort 3/5

#313 Fix/retry as bool
  CHANGELOG.md
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
  Sources/SmileID/Classes/Networking/Models/PrepUpload.swift
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort 2/5

#314 Require re-capture when retrying failed submission
  CHANGELOG.md
  Sources/SmileID/Classes/FaceDetector/LivenessCheckManager.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
Labels: Review effort 2/5

#319 Fix onFinished Error Callback Order
  Example/SmileID/EnhancedKYC/EnhancedKycWithIdInputScreenViewModel.swift
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
Labels: Review effort 2/5

#318 Enhanced KYC Metadata
  Sources/SmileID/Classes/Metadata/MetadataManager.swift
  Sources/SmileID/Classes/Metadata/NetworkMetadataProvider.swift
  Sources/SmileID/Classes/Networking/Models/EnhancedKyc.swift
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort 2/5

#317 Metadata: Wrapper Name & Version
  Sources/SmileID/Classes/Metadata/MetadataKey.swift
  Sources/SmileID/Classes/Metadata/MetadataModels.swift
  Sources/SmileID/Classes/Metadata/NetworkMetadataProvider.swift
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort 1/5

#315 Metadata: Environment and Device Information
  Example/Podfile.lock
  SmileID.xcodeproj/project.pbxproj
  Sources/SmileID/Classes/DocumentVerification/Model/DocumentCaptureViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
  Sources/SmileID/Classes/Helpers/JSONUtils.swift
  Sources/SmileID/Classes/Metadata/DeviceOrientationMetadataProvider.swift
  Sources/SmileID/Classes/Metadata/MetadataKey.swift
  Sources/SmileID/Classes/Metadata/MetadataManager.swift
  Sources/SmileID/Classes/Metadata/NetworkMetadataProvider.swift
  Sources/SmileID/Classes/Metadata/ProcessInfoExtension.swift
  Sources/SmileID/Classes/Metadata/UIScreenExtension.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
Labels: Review effort 2/5

#316 Metadata: Sensor and Behavioural Info
  Sources/SmileID/Classes/DocumentVerification/Model/DocumentCaptureViewModel.swift
  Sources/SmileID/Classes/Helpers/DateUtils.swift
  Sources/SmileID/Classes/Metadata/AVCaptureDeviceExtension.swift
  Sources/SmileID/Classes/Metadata/BundleExtension.swift
  Sources/SmileID/Classes/Metadata/DeviceOrientationMetadataProvider.swift
  Sources/SmileID/Classes/Metadata/MetadataKey.swift
  Sources/SmileID/Classes/Metadata/MetadataManager.swift
  Sources/SmileID/Classes/Metadata/UIDeviceExtension.swift
  Sources/SmileID/Classes/Metadata/UIDeviceOrientationExtension.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort 2/5

#321 Metadata: Network Retries and Security Policy Version
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
  Sources/SmileID/Classes/Metadata/MetadataKey.swift
  Sources/SmileID/Classes/Metadata/MetadataManager.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
Labels: Review effort 2/5

#323 Metadata: Strings to Value Data Types
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/DocumentCaptureViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
  Sources/SmileID/Classes/Helpers/CodableValue.swift
  Sources/SmileID/Classes/Helpers/TimeIntervalExtensions.swift
  Sources/SmileID/Classes/Metadata/AVCaptureDeviceExtension.swift
  Sources/SmileID/Classes/Metadata/DeviceOrientationMetadataProvider.swift
  Sources/SmileID/Classes/Metadata/MetadataManager.swift
  Sources/SmileID/Classes/Metadata/Metadatum.swift
  Sources/SmileID/Classes/Metadata/NetworkMetadataProvider.swift
  Sources/SmileID/Classes/Metadata/ProcessInfoExtension.swift
  Sources/SmileID/Classes/Metadata/UIDeviceExtension.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort 2/5
