Repository smileidentity/ios, pull requests merged in 2025-07, with the labels that each got.

#350 Update Secure Version 🦞
  Example/Podfile.lock
  Package.resolved
  Package.swift
  SmileID.podspec
Labels: Review effort 1/5

#338 Fix: Return Absolute File Path instead of Relative File Path for Files
  CHANGELOG.md
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
  Sources/SmileID/Classes/Util.swift
Labels: Review effort 3/5

#353 Add Scene Delegate and Scene Manifest
  Example/Podfile.lock
  Example/SmileID.xcodeproj/project.pbxproj
  Example/SmileID.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Example/SmileID/App/AppDelegate.swift
  Example/SmileID/App/SceneDelegate.swift
  Example/SmileID/Info.plist
Labels: Review effort 3/5

#354 Prepare Release 11.0.2
  CHANGELOG.md
  Example/Podfile.lock
  SmileID.podspec
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort 1/5

#347 Sentry integration for iOS SDK
  .github/workflows/sdk-primary.yml
  .gitignore
  Example/.arkana.yml
  Example/Podfile
  Example/Podfile.lock
  Example/SmileID.xcodeproj/project.pbxproj
  Example/SmileID.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Example/SmileID/App/SceneDelegate.swift
  Example/SmileID/Home/HomeViewModel.swift
  Gemfile.lock
  Package.resolved
  Package.swift
  Rakefile
  SmileID.podspec
  SmileID.xcodeproj/project.pbxproj
  SmileID.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
  Sources/SmileID/Classes/Keys/ArkanaKeys.swift
  Sources/SmileID/Classes/Keys/ArkanaKeysInterfaces.swift
  Sources/SmileID/Classes/Networking/URLSession/URLSessionRestServiceClient.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
  Sources/SmileID/Classes/SmileID.swift
  Sources/SmileID/Classes/SmileIDCrashReporting.swift
  Sources/SmileID/Classes/Util.swift
Labels: Review effort 4/5

#358 Updated Changelog and Sentry Config 🌻
  CHANGELOG.md
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort 2/5

#360 Remove Default Consent Information 🦁
  CHANGELOG.md
  Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreenViewModel.swift
  Example/SmileID/BiometricKYC/IdInfoInputScreen.swift
  Example/SmileID/BiometricKYC/IdInfoInputViewModel.swift
  Example/SmileID/EnhancedKYC/EnhancedKycWithIdInputScreenViewModel.swift
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift
  Sources/SmileID/Classes/Networking/Models/EnhancedKyc.swift
  Sources/SmileID/Classes/SmileID.swift
Labels: Review effort 3/5

#362 Refactor SelfieViewModel
  Sources/SmileID/Classes/Helpers/DebugUtils.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
Labels: Review effort 4/5

#368 Fix Latest Xcode Cloud Failures
  Example/SmileID.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Review effort 1/5
