Repository smileidentity/ios, pull requests merged in 2025-05, with the labels that each got.

#324 Metadata: Event-like Payload Structure
  Sources/SmileID/Classes/Metadata/DeviceOrientationMetadataProvider.swift
  Sources/SmileID/Classes/Metadata/MetadataManager.swift
  Sources/SmileID/Classes/Metadata/Metadatum.swift
  Sources/SmileID/Classes/Metadata/NetworkMetadataProvider.swift
Labels: Review effort 3/5

#325 Scope MetadataManager to SDK
  Sources/SmileID/Classes/Metadata/MetadataManager.swift
  Sources/SmileID/Classes/Metadata/NetworkMetadataProvider.swift
  Sources/SmileID/Classes/Networking/ServiceRunnable.swift
  Sources/SmileID/Classes/Networking/SmileIDService.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieSubmissionManager.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
  Sources/SmileID/Classes/SmileID.swift
  Tests/Mocks/NetworkingMocks.swift
Labels: Review effort 2/5

#326 feat: consent info correct mapping
  CHANGELOG.md
  Example/SmileID/BiometricKYC/BiometricKycWithIdInputScreenViewModel.swift
  Example/SmileID/BiometricKYC/IdInfoInputScreen.swift
  Example/SmileID/DocumentVerification/EnhancedDocumentVerificationWithSelector.swift
  Example/SmileID/EnhancedKYC/EnhancedKycWithIdInputScreenViewModel.swift
  Sources/SmileID/Classes/Consent/OrchestratedConsentScreen.swift
  Sources/SmileID/Classes/Networking/Models/EnhancedKyc.swift
  Sources/SmileID/Classes/Networking/Models/UploadRequest.swift
  Sources/SmileID/Classes/SmileID.swift
  Tests/Networking/EnhancedKycTest.swift
  Tests/Networking/Model/ConsentInformationTests.swift
Labels: Review effort 2/5

#329 fix typo
  CHANGELOG.md
  Sources/SmileID/Resources/Localization/en.lproj/Localizable.strings
Labels: Review effort 1/5

#333 Make Calculate Signature Public 🦅
  CHANGELOG.md
  Sources/SmileID/Classes/Networking/NetworkUtil.swift
Labels: Review effort 1/5

#330 Fix Device Orientation Metadata, Use native ISODateFormatter.
  Sources/SmileID/Classes/Helpers/DateUtils.swift
  Sources/SmileID/Classes/Metadata/Providers/DeviceOrientationMetadata.swift
Labels: Review effort 2/5

#327 Fraud signals metadata
  CHANGELOG.md
  Example/Podfile.lock
  Example/SmileID/Home/HomeViewModel.swift
  Example/SmileID/Info.plist
  SmileID.xcodeproj/project.pbxproj
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycScreen.swift
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/DocumentCaptureViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/View/DocumentCaptureScreen.swift
  Sources/SmileID/Classes/DocumentVerification/View/OrchestratedDocumentVerificationScreen.swift
  Sources/SmileID/Classes/Helpers/CodableValue.swift
  Sources/SmileID/Classes/Helpers/DateUtils.swift
  Sources/SmileID/Classes/Helpers/JSONUtils.swift
  Sources/SmileID/Classes/Helpers/LocalStorage.swift
  Sources/SmileID/Classes/Helpers/TimeIntervalExtensions.swift
  Sources/SmileID/Classes/Metadata/Device/AVCaptureDeviceExtension.swift
  Sources/SmileID/Classes/Metadata/Device/BundleExtension.swift
  Sources/SmileID/Classes/Metadata/Device/IPAddressProvider.swift
  Sources/SmileID/Classes/Metadata/Device/LocationMetadata.swift
  Sources/SmileID/Classes/Metadata/Device/ProcessInfoExtension.swift
  Sources/SmileID/Classes/Metadata/Device/ProxyMetadata.swift
  Sources/SmileID/Classes/Metadata/Device/UIDeviceExtension.swift
  Sources/SmileID/Classes/Metadata/Device/UIScreenExtension.swift
  Sources/SmileID/Classes/Metadata/Device/VpnMetadata.swift
  Sources/SmileID/Classes/Metadata/Metadata.swift
  Sources/SmileID/Classes/Metadata/Models/MetadataKey.swift
  Sources/SmileID/Classes/Metadata/Models/MetadataModels.swift
  Sources/SmileID/Classes/Metadata/Models/Metadatum.swift
  Sources/SmileID/Classes/Metadata/Providers/DeviceOrientationMetadata.swift
  Sources/SmileID/Classes/Metadata/Providers/MetadataProtocol.swift
  Sources/SmileID/Classes/Metadata/Providers/NetworkMetadata.swift
  Sources/SmileID/Classes/Networking/Models/EnhancedKyc.swift
  Sources/SmileID/Classes/Networking/Models/v2/Metadata.swift
  Sources/SmileID/Classes/Networking/ServiceRunnable.swift
  Sources/SmileID/Classes/Networking/SmileIDService.swift
  Sources/SmileID/Classes/SelfieCapture/EnhancedSmartSelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieSubmissionManager.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
  Sources/SmileID/Classes/SelfieCapture/View/OrchestratedEnhancedSelfieCaptureScreen.swift
  Sources/SmileID/Classes/SelfieCapture/View/OrchestratedSelfieCaptureScreen.swift
  Sources/SmileID/Classes/SmileID.swift
  Sources/SmileID/Classes/Util.swift
  Tests/Mocks/NetworkingMocks.swift
Labels: Review effort 4/5

#286 Feat/integrate smile security module
  CHANGELOG.md
  Example/Podfile.lock
  Example/SmileID.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  SmileID.podspec
  SmileID.xcodeproj/project.pbxproj
  SmileID.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sources/SmileID/Classes/BiometricKYC/OrchestratedBiometricKycViewModel.swift
  Sources/SmileID/Classes/DocumentVerification/Model/OrchestratedDocumentVerificationViewModel.swift
  Sources/SmileID/Classes/Helpers/LocalStorage.swift
  Sources/SmileID/Classes/Networking/Models/FailureReason.swift
  Sources/SmileID/Classes/Networking/Models/MultipartBody.swift
  Sources/SmileID/Classes/Networking/Models/PrepUpload.swift
  Sources/SmileID/Classes/Networking/Models/SecurityInfo.swift
  Sources/SmileID/Classes/Networking/Models/SelfieRequest.swift
  Sources/SmileID/Classes/Networking/ServiceHeaderProvider.swift
  Sources/SmileID/Classes/Networking/ServiceRunnable.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieSubmissionManager.swift
  Sources/SmileID/Classes/SelfieCapture/SelfieViewModel.swift
  Sources/SmileID/Classes/SmileID.swift
  Tests/Networking/Model/ConsentInformationTests.swift
Labels: Review effort 3/5
