Repository smileidentity/ios, pull requests merged in 2025-08, with the labels that each got.

#377 Add Internal Modules
  Example/SmileID.xcodeproj/project.pbxproj
  Example/SmileID.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Example/SmileID_Example.entitlements
  Package.swift
  SmileID.podspec
  SmileIDAnalytics/SmileIDAnalytics.swift
  SmileIDCamera/SmileIDCamera.swift
  SmileIDML/SmileIDML.swift
  SmileIDNetworking/SmileIDNetworking.swift
  SmileIDStorage/SmileIDStorage.swift
  SmileIDUI/SmileIDUI.swift
Labels: Review effort 3/5

#378 Setup Instructions Screen with custom styles.
  Package.swift
  SmileIDUI/Components/SmileIDButton.swift
  SmileIDUI/SmileIDInstructionsScreen.swift
  SmileIDUI/SmileIDUI.swift
  SmileIDUI/Tests/SmileIDInstructionsScreenTests.swift
Labels: Review effort 2/5

#379 Setup Capture and Preview
  Package.swift
  SmileIDAnalytics/Classes/SmileIDAnalytics.swift
  SmileIDAnalytics/Tests/SmileIDAnalyticsTests.swift
  SmileIDCamera/Classes/SmileIDCamera.swift
  SmileIDCamera/Tests/SmileIDCameraTests.swift
  SmileIDML/Classes/SmileIDML.swift
  SmileIDML/Tests/SmileIDMLTests.swift
  SmileIDNetworking/Classes/SmileIDNetworking.swift
  SmileIDNetworking/Tests/SmileIDNetworkingTests.swift
  SmileIDStorage/Classes/SmileIDStorage.swift
  SmileIDStorage/Tests/SmileIDStorageTests.swift
  SmileIDUI/Classes/Components/DocumentShapedView.swift
  SmileIDUI/Classes/Components/FaceShapedView.swift
  SmileIDUI/Classes/Components/SmileIDButton.swift
  SmileIDUI/Classes/Components/SmileIDCameraPreview.swift
  SmileIDUI/Classes/ScanType.swift
  SmileIDUI/Classes/SmileIDCaptureScreen.swift
  SmileIDUI/Classes/SmileIDInstructionsScreen.swift
  SmileIDUI/Tests/SmileIDCaptureScreenTests.swift
Labels: Review effort 2/5

#380 Setup Processing and Preview Screens
  SmileIDUI/Classes/SmileIDPreviewScreen.swift
  SmileIDUI/Classes/SmileIDProcessingScreen.swift
  SmileIDUI/Tests/SmileIDPreviewScreenTests.swift
  SmileIDUI/Tests/SmileIDProcessingScreenTests.swift
Labels: Review effort 2/5

#383 UIKit Presentation Helpers
  Example-Objc/Example-Objc.xcodeproj/project.pbxproj
  Example-Objc/Example-Objc.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Example-Objc/Example-Objc/Base.lproj/Main.storyboard
  Example-Objc/Example-Objc/SmileID/SmileIDUIKitTestViewController.swift
  Example-Objc/Example-Objc/ViewController.m
  SmileIDNavigation/Classes/VerificationFlowPresenter.swift
  SmileIDUI/Classes/SmileIDUIKitHelpers.swift
Labels: Review effort 2/5

#388 Disable Back Buttons on Verification Flows
  Example/SmileID/Settings/VerificationDemoView.swift
  SmileIDNavigation/Classes/PushNavigationContainer.swift
  SmileIDNavigation/Classes/VerificationFlowView.swift
Labels: Review effort 2/5

#390 flatten build info
  Sources/Classes/Metadata/Device/BuildInfo.swift
  Sources/Classes/Metadata/Metadata.swift
  Sources/Classes/Metadata/Models/MetadataKey.swift
Labels: Review effort 2/5

#391 add package name to metadata
  Sources/Classes/Metadata/Metadata.swift
  Sources/Classes/Metadata/Models/MetadataKey.swift
Labels: Review effort 2/5

#389 Setup ViewModels for Verification Flows
  SmileIDNavigation/Classes/Helpers/Backport.swift
  SmileIDNavigation/Classes/Helpers/StateObject.swift
  SmileIDNavigation/Classes/VerificationCoordinator.swift
  SmileIDNavigation/Classes/VerificationDemoView.swift
  SmileIDNavigation/Classes/VerificationFlowView.swift
  SmileIDNavigation/Classes/ViewModels/VerificationDemoViewModel.swift
  SmileIDNavigation/Classes/ViewModels/VerificationFlowState.swift
  SmileIDNavigation/Classes/ViewModels/VerificationFlowViewModel.swift
  SmileIDNavigation/Tests/SmileIDNavigationTests.swift
  SmileIDUI/Classes/Helpers/Backport.swift
  SmileIDUI/Classes/Helpers/StateObject.swift
  SmileIDUI/Classes/SmileIDCaptureScreen.swift
  SmileIDUI/Classes/SmileIDPreviewScreen.swift
  SmileIDUI/Classes/SmileIDProcessingScreen.swift
  SmileIDUI/Classes/ViewModels/CaptureScreenViewModel.swift
  SmileIDUI/Classes/ViewModels/PreviewScreenViewModel.swift
  SmileIDUI/Classes/ViewModels/ProcessingScreenViewModel.swift
Labels: Review effort 4/5
